name: Client CI/CD

on:
  push:
    paths:
      - 'apps/client/**'
      # - 'packages/shared/**'
  pull_request:
    paths:
      - 'apps/client/**'
      # - 'packages/shared/**'

jobs:
  build-deploy-client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Client
        run: npm run build

      # Здесь можешь вставить свой деплой. Например, деплой на Vercel:
      # - name: Deploy to Vercel
      #   run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
